CREATE OR REPLACE PACKAGE PKG_MERG_CLIENT_EMAM AS
    PROCEDURE SP_GENERATE_CLIENT_ID(
      P_CLIENT_NAME IN VARCHAR2, P_CLIENT_ID OUT VARCHAR2
      );
    PROCEDURE SP_SAVE_CLIENT_DETAILS(
      P_CLIENT_ID IN VARCHAR2,
      P_CLIENT_FATHER_NAME IN VARCHAR2,
      P_CLIENT_MOTHER_NAME IN VARCHAR2, 
      P_CLIENT_DATE_OF_BIRTH IN DATE, 
      P_CLIENT_GENDER IN VARCHAR2, 
      P_CLIENT_MARITAL_STATUS IN VARCHAR2, 
      P_CLIENT_SPOUSE_NAME IN VARCHAR2, 
      P_CLIENT_NID IN NUMBER
      );
    PROCEDURE SP_SAVE_ADDRESS_CONTACT(
      P_CLIENT_ID IN VARCHAR2, 
      P_ADDRESS_TYPE_ID IN VARCHAR2, 
      P_COUNTRY_ID IN VARCHAR2, 
      P_DIVISION_ID IN VARCHAR2, 
      P_DISTRICT_ID IN VARCHAR2, 
      P_THANA_ID IN VARCHAR2, 
      P_CITY IN VARCHAR2, 
      P_ZIP IN VARCHAR2, 
      P_MOBILE IN VARCHAR2, 
      P_EMAIL IN VARCHAR2, 
      P_ADDRESS IN VARCHAR2
      );
    PROCEDURE SP_SAVE_ACCOUNT(
      P_CLIENT_ID IN VARCHAR2, 
      P_OFFICE_CODE IN VARCHAR2, 
      P_ACCOUNT_NO IN VARCHAR2, 
      P_ACCOUNT_TITLE IN VARCHAR2, 
      P_ACCOUNT_OPEN_DATE IN DATE, 
      P_ACCOUNT_EXPIRY_DATE IN DATE, 
      P_LIMIT_AMOUNT IN NUMBER
      );
    PROCEDURE SP_GET_ALL_CLIENTS(
      P_CURSOR OUT SYS_REFCURSOR
      );
    PROCEDURE SP_GET_CLIENT_BY_ID(
      P_CLIENT_ID IN VARCHAR2, 
      P_CURSOR OUT SYS_REFCURSOR
      );
    PROCEDURE SP_GET_CLIENT_DETAILS(
      P_CLIENT_ID IN VARCHAR2, 
      P_CURSOR OUT SYS_REFCURSOR
      );
    PROCEDURE SP_GET_CLIENT_ADDRESS(
      P_CLIENT_ID IN VARCHAR2, 
      P_CURSOR OUT SYS_REFCURSOR
      );
    PROCEDURE SP_GET_CLIENT_ACCOUNT(
      P_CLIENT_ID IN VARCHAR2, 
      P_CURSOR OUT SYS_REFCURSOR
      );
    PROCEDURE SP_GET_ADDRESS_TYPES(
      P_CURSOR OUT SYS_REFCURSOR
      );
    PROCEDURE SP_GET_COUNTRIES(
      P_CURSOR OUT SYS_REFCURSOR
      );
    PROCEDURE SP_GET_DIVISIONS(
      P_COUNTRY_ID IN VARCHAR2, 
      P_CURSOR OUT SYS_REFCURSOR
      );
    PROCEDURE SP_GET_DISTRICTS(
      P_DIVISIONS_ID IN VARCHAR2, 
      P_CURSOR OUT SYS_REFCURSOR
      );
    PROCEDURE SP_GET_THANAS(
      P_DISTRICTS_ID IN VARCHAR2, 
      P_CURSOR OUT SYS_REFCURSOR
      );
    PROCEDURE SP_DELETE_CLIENT(
      P_CLIENT_ID IN VARCHAR2
      );
    PROCEDURE SP_DELETE_CLIENT_ADDRESS(
      P_CLIENT_ID IN VARCHAR2
      );
    PROCEDURE SP_DELETE_CLIENT_ACCOUNT(
      P_CLIENT_ID IN VARCHAR2
      );
    PROCEDURE SP_UPDATE_CLIENT_INFO(
      P_CLIENT_ID IN VARCHAR2, 
      P_CLIENT_NAME IN VARCHAR2
      );
    PROCEDURE SP_UPDATE_CLIENT_DETAILS(
      P_CLIENT_ID IN VARCHAR2, 
      P_CLIENT_FATHER_NAME IN VARCHAR2, 
      P_CLIENT_MOTHER_NAME IN VARCHAR2, 
      P_CLIENT_DATE_OF_BIRTH IN DATE, 
      P_CLIENT_GENDER IN VARCHAR2, 
      P_CLIENT_MARITAL_STATUS IN VARCHAR2, 
      P_CLIENT_SPOUSE_NAME IN VARCHAR2, 
      P_CLIENT_NID IN NUMBER
      );
    PROCEDURE SP_UPDATE_ADDRESS_CONTACT(
      P_CLIENT_ID IN VARCHAR2, 
      P_ADDRESS_TYPE_ID IN VARCHAR2, 
      P_COUNTRY_ID IN VARCHAR2, 
      P_DIVISION_ID IN VARCHAR2, 
      P_DISTRICT_ID IN VARCHAR2, 
      P_THANA_ID IN VARCHAR2, 
      P_CITY IN VARCHAR2, 
      P_ZIP IN VARCHAR2, 
      P_MOBILE IN VARCHAR2, 
      P_EMAIL IN VARCHAR2, 
      P_ADDRESS IN VARCHAR2
      );
    PROCEDURE SP_UPDATE_ACCOUNT(
      P_CLIENT_ID IN VARCHAR2, 
      P_OFFICE_CODE IN VARCHAR2, 
      P_ACCOUNT_NO IN VARCHAR2, 
      P_ACCOUNT_TITLE IN VARCHAR2, 
      P_ACCOUNT_OPEN_DATE IN DATE, 
      P_ACCOUNT_EXPIRY_DATE IN DATE, 
      P_LIMIT_AMOUNT IN NUMBER
      );
END PKG_MERG_CLIENT_EMAM;

