CREATE OR REPLACE PACKAGE BODY PKG_MERG_CLIENT_EMAM AS

    PROCEDURE SP_GENERATE_CLIENT_ID(
        P_CLIENT_NAME IN VARCHAR2,
        P_CLIENT_ID OUT VARCHAR2
    ) AS
        V_NEXT_ID NUMBER;
    BEGIN
        SELECT NVL(MAX(TO_NUMBER(CLIENT_ID)), 999) + 1
          INTO V_NEXT_ID
          FROM CLIENT_INFO_EMAM
         WHERE REGEXP_LIKE(CLIENT_ID, '^[0-9]+$');

        INSERT INTO CLIENT_INFO_EMAM (CLIENT_ID, CLIENT_NAME)
        VALUES (TO_CHAR(V_NEXT_ID), TRIM(P_CLIENT_NAME));

        P_CLIENT_ID := TO_CHAR(V_NEXT_ID);
        COMMIT;
    END SP_GENERATE_CLIENT_ID;

    PROCEDURE SP_SAVE_CLIENT_DETAILS(
        P_CLIENT_ID IN VARCHAR2,
        P_CLIENT_FATHER_NAME IN VARCHAR2,
        P_CLIENT_MOTHER_NAME IN VARCHAR2,
        P_CLIENT_DATE_OF_BIRTH IN DATE,
        P_CLIENT_GENDER IN VARCHAR2,
        P_CLIENT_MARITAL_STATUS IN VARCHAR2,
        P_CLIENT_SPOUSE_NAME IN VARCHAR2,
        P_CLIENT_NID IN NUMBER
    ) AS
    BEGIN
        INSERT INTO CLIENT_DETAILS_EMAM (
            CLIENT_ID, FATHER_NAME, MOTHER_NAME, DATE_OF_BIRTH,
            GENDER, MARITAL_STATUS, SPOUSE_NAME, NID
        )
        VALUES (
            P_CLIENT_ID, TRIM(P_CLIENT_FATHER_NAME), TRIM(P_CLIENT_MOTHER_NAME),
            P_CLIENT_DATE_OF_BIRTH, UPPER(TRIM(P_CLIENT_GENDER)),
            TRIM(P_CLIENT_MARITAL_STATUS), TRIM(P_CLIENT_SPOUSE_NAME),
            P_CLIENT_NID
        );

        COMMIT;
    END SP_SAVE_CLIENT_DETAILS;

    PROCEDURE SP_SAVE_ADDRESS_CONTACT(
        P_CLIENT_ID IN VARCHAR2,
        P_ADDRESS_TYPE_ID IN VARCHAR2,
        P_COUNTRY_ID IN VARCHAR2,
        P_DIVISION_ID IN VARCHAR2,
        P_DISTRICT_ID IN VARCHAR2,
        P_THANA_ID IN VARCHAR2,
        P_CITY IN VARCHAR2,
        P_ZIP IN VARCHAR2,
        P_MOBILE IN VARCHAR2,
        P_EMAIL IN VARCHAR2,
        P_ADDRESS IN VARCHAR2
    ) AS
    BEGIN
        INSERT INTO ADDRESS_CONTACT_EMAM (
            CLIENT_ID, ADDRESS_TYPE, COUNTRY, DIVISION, DISTRICT,
            THANA, CITY, ZIP_CODE, MOBILE_NO, EMAIL, ADDRESS
        )
        VALUES (
            P_CLIENT_ID, P_ADDRESS_TYPE_ID, P_COUNTRY_ID, P_DIVISION_ID,
            P_DISTRICT_ID, P_THANA_ID, TRIM(P_CITY), TRIM(P_ZIP),
            TRIM(P_MOBILE), TRIM(P_EMAIL), TRIM(P_ADDRESS)
        );

        COMMIT;
    END SP_SAVE_ADDRESS_CONTACT;

    PROCEDURE SP_SAVE_ACCOUNT(
        P_CLIENT_ID IN VARCHAR2,
        P_OFFICE_CODE IN VARCHAR2,
        P_ACCOUNT_NO IN VARCHAR2,
        P_ACCOUNT_TITLE IN VARCHAR2,
        P_ACCOUNT_OPEN_DATE IN DATE,
        P_ACCOUNT_EXPIRY_DATE IN DATE,
        P_LIMIT_AMOUNT IN NUMBER
    ) AS
    BEGIN
        INSERT INTO ACCOUNT_INFO_EMAM (
            CLIENT_ID, OFFICE_CODE, ACCOUNT_NO, ACCOUNT_TITLE,
            ACCOUNT_OPEN_DATE, ACCOUNT_EXPIRY_DATE, LIMIT_AMOUNT
        )
        VALUES (
            P_CLIENT_ID, TRIM(P_OFFICE_CODE), TRIM(P_ACCOUNT_NO),
            TRIM(P_ACCOUNT_TITLE), P_ACCOUNT_OPEN_DATE,
            P_ACCOUNT_EXPIRY_DATE, P_LIMIT_AMOUNT
        );

        COMMIT;
    END SP_SAVE_ACCOUNT;

    PROCEDURE SP_GET_ALL_CLIENTS(P_CURSOR OUT SYS_REFCURSOR) AS
    BEGIN
        OPEN P_CURSOR FOR
            SELECT
                CI.CLIENT_ID,
                CI.CLIENT_NAME,
                CD.FATHER_NAME,
                CD.MOTHER_NAME,
                CD.DATE_OF_BIRTH,
                CD.GENDER,
                CD.MARITAL_STATUS,
                CD.SPOUSE_NAME,
                CD.NID,
                AC.ADDRESS_TYPE,
                AC.COUNTRY,
                AC.DIVISION,
                AC.DISTRICT,
                AC.THANA,
                AC.CITY,
                AC.ZIP_CODE,
                AC.MOBILE_NO,
                AC.EMAIL,
                AC.ADDRESS,
                AI.OFFICE_CODE,
                AI.ACCOUNT_NO,
                AI.ACCOUNT_TITLE,
                AI.ACCOUNT_OPEN_DATE,
                AI.ACCOUNT_EXPIRY_DATE,
                AI.LIMIT_AMOUNT
            FROM CLIENT_INFO_EMAM CI
            LEFT JOIN CLIENT_DETAILS_EMAM CD ON CI.CLIENT_ID = CD.CLIENT_ID
            LEFT JOIN ADDRESS_CONTACT_EMAM AC ON CI.CLIENT_ID = AC.CLIENT_ID
            LEFT JOIN ACCOUNT_INFO_EMAM AI ON CI.CLIENT_ID = AI.CLIENT_ID
            ORDER BY
                CASE
                    WHEN REGEXP_LIKE(CI.CLIENT_ID, '^[0-9]+$')
                    THEN TO_NUMBER(CI.CLIENT_ID)
                END DESC NULLS LAST,
                CI.CLIENT_ID DESC;
    END SP_GET_ALL_CLIENTS;

    PROCEDURE SP_GET_CLIENT_BY_ID(P_CLIENT_ID IN VARCHAR2, P_CURSOR OUT SYS_REFCURSOR) AS
    BEGIN
        OPEN P_CURSOR FOR
            SELECT CLIENT_ID, CLIENT_NAME
              FROM CLIENT_INFO_EMAM
             WHERE CLIENT_ID = P_CLIENT_ID;
    END SP_GET_CLIENT_BY_ID;

    PROCEDURE SP_GET_CLIENT_DETAILS(P_CLIENT_ID IN VARCHAR2, P_CURSOR OUT SYS_REFCURSOR) AS
    BEGIN
        OPEN P_CURSOR FOR
            SELECT *
              FROM CLIENT_DETAILS_EMAM
             WHERE CLIENT_ID = P_CLIENT_ID;
    END SP_GET_CLIENT_DETAILS;

    PROCEDURE SP_GET_CLIENT_ADDRESS(P_CLIENT_ID IN VARCHAR2, P_CURSOR OUT SYS_REFCURSOR) AS
    BEGIN
        OPEN P_CURSOR FOR
            SELECT *
              FROM ADDRESS_CONTACT_EMAM
             WHERE CLIENT_ID = P_CLIENT_ID;
    END SP_GET_CLIENT_ADDRESS;

    PROCEDURE SP_GET_CLIENT_ACCOUNT(P_CLIENT_ID IN VARCHAR2, P_CURSOR OUT SYS_REFCURSOR) AS
    BEGIN
        OPEN P_CURSOR FOR
            SELECT *
              FROM ACCOUNT_INFO_EMAM
             WHERE CLIENT_ID = P_CLIENT_ID;
    END SP_GET_CLIENT_ACCOUNT;

    PROCEDURE SP_GET_ADDRESS_TYPES(P_CURSOR OUT SYS_REFCURSOR) AS
    BEGIN
        OPEN P_CURSOR FOR SELECT * FROM ADDRESS_TYPE_EMAM;
    END SP_GET_ADDRESS_TYPES;

    PROCEDURE SP_GET_COUNTRIES(P_CURSOR OUT SYS_REFCURSOR) AS
    BEGIN
        OPEN P_CURSOR FOR SELECT * FROM COUNTRY_NAME_EMAM;
    END SP_GET_COUNTRIES;

    PROCEDURE SP_GET_DIVISIONS(P_COUNTRY_ID IN VARCHAR2, P_CURSOR OUT SYS_REFCURSOR) AS
    BEGIN
        OPEN P_CURSOR FOR
            SELECT *
              FROM DIVISION_NAME_EMAM
             WHERE COUNTRY_ID = P_COUNTRY_ID;
    END SP_GET_DIVISIONS;

    PROCEDURE SP_GET_DISTRICTS(P_DIVISIONS_ID IN VARCHAR2, P_CURSOR OUT SYS_REFCURSOR) AS
    BEGIN
        OPEN P_CURSOR FOR
            SELECT *
              FROM DISTRICT_NAME_EMAM
             WHERE DIVISION_ID = P_DIVISIONS_ID;
    END SP_GET_DISTRICTS;

    PROCEDURE SP_GET_THANAS(P_DISTRICTS_ID IN VARCHAR2, P_CURSOR OUT SYS_REFCURSOR) AS
    BEGIN
        OPEN P_CURSOR FOR
            SELECT *
              FROM THANA_NAME_EMAM
             WHERE DISTRICT_ID = P_DISTRICTS_ID;
    END SP_GET_THANAS;

    PROCEDURE SP_DELETE_CLIENT(P_CLIENT_ID IN VARCHAR2) AS
    BEGIN
        DELETE FROM ADDRESS_CONTACT_EMAM WHERE CLIENT_ID = P_CLIENT_ID;
        DELETE FROM ACCOUNT_INFO_EMAM WHERE CLIENT_ID = P_CLIENT_ID;
        DELETE FROM CLIENT_DETAILS_EMAM WHERE CLIENT_ID = P_CLIENT_ID;
        DELETE FROM CLIENT_INFO_EMAM WHERE CLIENT_ID = P_CLIENT_ID;
        COMMIT;
    END SP_DELETE_CLIENT;

    PROCEDURE SP_DELETE_CLIENT_ADDRESS(P_CLIENT_ID IN VARCHAR2) AS
    BEGIN
        DELETE FROM ADDRESS_CONTACT_EMAM WHERE CLIENT_ID = P_CLIENT_ID;
        COMMIT;
    END SP_DELETE_CLIENT_ADDRESS;

    PROCEDURE SP_DELETE_CLIENT_ACCOUNT(P_CLIENT_ID IN VARCHAR2) AS
    BEGIN
        DELETE FROM ACCOUNT_INFO_EMAM WHERE CLIENT_ID = P_CLIENT_ID;
        COMMIT;
    END SP_DELETE_CLIENT_ACCOUNT;

    PROCEDURE SP_UPDATE_CLIENT_INFO(P_CLIENT_ID IN VARCHAR2, P_CLIENT_NAME IN VARCHAR2) AS
    BEGIN
        UPDATE CLIENT_INFO_EMAM
           SET CLIENT_NAME = TRIM(P_CLIENT_NAME)
         WHERE CLIENT_ID = P_CLIENT_ID;
        COMMIT;
    END SP_UPDATE_CLIENT_INFO;

    PROCEDURE SP_UPDATE_CLIENT_DETAILS(
        P_CLIENT_ID IN VARCHAR2,
        P_CLIENT_FATHER_NAME IN VARCHAR2,
        P_CLIENT_MOTHER_NAME IN VARCHAR2,
        P_CLIENT_DATE_OF_BIRTH IN DATE,
        P_CLIENT_GENDER IN VARCHAR2,
        P_CLIENT_MARITAL_STATUS IN VARCHAR2,
        P_CLIENT_SPOUSE_NAME IN VARCHAR2,
        P_CLIENT_NID IN NUMBER
    ) AS
    BEGIN
        UPDATE CLIENT_DETAILS_EMAM
           SET FATHER_NAME = TRIM(P_CLIENT_FATHER_NAME),
               MOTHER_NAME = TRIM(P_CLIENT_MOTHER_NAME),
               DATE_OF_BIRTH = P_CLIENT_DATE_OF_BIRTH,
               GENDER = UPPER(TRIM(P_CLIENT_GENDER)),
               MARITAL_STATUS = TRIM(P_CLIENT_MARITAL_STATUS),
               SPOUSE_NAME = TRIM(P_CLIENT_SPOUSE_NAME),
               NID = P_CLIENT_NID
         WHERE CLIENT_ID = P_CLIENT_ID;
        COMMIT;
    END SP_UPDATE_CLIENT_DETAILS;

    PROCEDURE SP_UPDATE_ADDRESS_CONTACT(
        P_CLIENT_ID IN VARCHAR2,
        P_ADDRESS_TYPE_ID IN VARCHAR2,
        P_COUNTRY_ID IN VARCHAR2,
        P_DIVISION_ID IN VARCHAR2,
        P_DISTRICT_ID IN VARCHAR2,
        P_THANA_ID IN VARCHAR2,
        P_CITY IN VARCHAR2,
        P_ZIP IN VARCHAR2,
        P_MOBILE IN VARCHAR2,
        P_EMAIL IN VARCHAR2,
        P_ADDRESS IN VARCHAR2
    ) AS
    BEGIN
        UPDATE ADDRESS_CONTACT_EMAM
           SET ADDRESS_TYPE = P_ADDRESS_TYPE_ID,
               COUNTRY = P_COUNTRY_ID,
               DIVISION = P_DIVISION_ID,
               DISTRICT = P_DISTRICT_ID,
               THANA = P_THANA_ID,
               CITY = TRIM(P_CITY),
               ZIP_CODE = TRIM(P_ZIP),
               MOBILE_NO = TRIM(P_MOBILE),
               EMAIL = TRIM(P_EMAIL),
               ADDRESS = TRIM(P_ADDRESS)
         WHERE CLIENT_ID = P_CLIENT_ID;
        COMMIT;
    END SP_UPDATE_ADDRESS_CONTACT;

    PROCEDURE SP_UPDATE_ACCOUNT(
        P_CLIENT_ID IN VARCHAR2,
        P_OFFICE_CODE IN VARCHAR2,
        P_ACCOUNT_NO IN VARCHAR2,
        P_ACCOUNT_TITLE IN VARCHAR2,
        P_ACCOUNT_OPEN_DATE IN DATE,
        P_ACCOUNT_EXPIRY_DATE IN DATE,
        P_LIMIT_AMOUNT IN NUMBER
    ) AS
    BEGIN
        UPDATE ACCOUNT_INFO_EMAM
           SET OFFICE_CODE = TRIM(P_OFFICE_CODE),
               ACCOUNT_NO = TRIM(P_ACCOUNT_NO),
               ACCOUNT_TITLE = TRIM(P_ACCOUNT_TITLE),
               ACCOUNT_OPEN_DATE = P_ACCOUNT_OPEN_DATE,
               ACCOUNT_EXPIRY_DATE = P_ACCOUNT_EXPIRY_DATE,
               LIMIT_AMOUNT = P_LIMIT_AMOUNT
         WHERE CLIENT_ID = P_CLIENT_ID;
        COMMIT;
    END SP_UPDATE_ACCOUNT;

END PKG_MERG_CLIENT_EMAM;
